[general]
import = [
    # "C:\\Users\\b1umx\\AppData\\Roaming\\alacritty\\themes\\kanagawa_wave.toml"
    "~/.config/alacritty/themes/kanagawa_wave.toml"
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[cursor.style]
blinking = "Off"
shape = "Beam"

[window]
# decorations = "None"
dynamic_padding = true
# opacity = 0.94
# startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 100
lines = 26

#[terminal.shell]
#program = "wsl"
# args = [
#     "-d", "Dev",
#     "--cd", "~",
#     "--",
#     "/bin/zsh", "-l",
#     "-c", "tmux attach || tmux"
