vim.g.mapleader = ','
local map = vim.api.nvim_set_keymap
local default_opts = { noremap = true, silent = true }

-- Window control
map('n', '<A-\\>', '<cmd>vsplit<cr>', default_opts)
map('n', '<A-/>', '<cmd>split<cr>', default_opts)
map('n', '<A-j>', '<cmd>wincmd j<cr>', default_opts)
map('n', '<A-k>', '<cmd>wincmd k<cr>', default_opts)
map('n', '<A-h>', '<cmd>wincmd h<cr>', default_opts)
map('n', '<A-l>', '<cmd>wincmd l<cr>', default_opts)
map('n', '<A-w>', '<cmd>wincmd w<cr>', default_opts)
map('n', '<A-W>', '<cmd>wincmd W<cr>', default_opts)
map('n', '<A-H>', '<cmd>wincmd <<cr>', default_opts)
map('n', '<A-L>', '<cmd>wincmd ><cr>', default_opts)
map('n', '<A-J>', '<cmd>wincmd -<cr>', default_opts)
map('n', '<A-K>', '<cmd>wincmd +<cr>', default_opts)
map('n', '<A-x>', '<cmd>wincmd c<cr>', default_opts)

-- Editor manipulation
map('n', '<C-Down>', '<cmd>m .+1<cr>==', default_opts)
map('n', '<C-Up>', '<cmd>m .-2<cr>==', default_opts)
map('i', '<C-Down>', '<Esc><cmd>m .+1<cr>==gi', default_opts)
map('i', '<C-Up>', '<Esc><cmd>m .-2<cr>==gi', default_opts)
map('v', '<C-Down>', '<cmd>m \'>+1<cr>gv=gv', default_opts)
map('v', '<C-Up>', '<cmd>m \'<-2<cr>gv=gv', default_opts)
map('n', '<Tab>', '>>', default_opts)
map('n', '<S-Tab>', '<<', default_opts)
map('v', '<Tab>', '>gv', default_opts)
map('v', '<S-Tab>', '<gv', default_opts)
map('n', '<C-s>', '<cmd>w<cr>', { noremap = true, silent = false })
map('i', '<C-s>', '<Esc><cmd>w<cr>', { noremap = true, silent = false })
map('n', '<A-e>', '<cmd>qa<cr>', default_opts)
map('n', '<A-n>', '<cmd>set nu! rnu!<cr>', default_opts)
map('n', '<C-h>', '<cmd>bp<cr>', { noremap = true, silent = false })
map('n', '<C-l>', '<cmd>bn<cr>', { noremap = true, silent = false })
map('n', '<C-d>', '"_dd<cr>', default_opts)
map('n', '<A-Up>', '<C-Y>', default_opts)
map('n', '<A-S-Up>', '<C-U>', default_opts)
map('n', '<A-Down>', '<C-E>', default_opts)
map('n', '<A-S-Down>', '<C-D>', default_opts)
map('n', '<A-Left>', 'zh', default_opts)
map('n', '<A-S-Left>', 'zH', default_opts)
map('n', '<A-Right>', 'zl', default_opts)
map('n', '<A-S-Right>', 'zL', default_opts)
vim.keymap.set('n', '<A-d>', vim.diagnostic.open_float, default_opts)
