require('options')
require('packages')
require('colors')
require('key-mapping')

require('packages/neodev-setup')
require('packages/bufferline-setup')
require('packages/nvim-tree-setup')
require('packages/lualine-setup')
require('packages/scrollbar-setup')
require('packages/gitsigns-setup')
require('packages/hlslens-setup')
require('packages/cmp-setup')
require('packages/luasnip-setup')
require('packages/lsp-setup')
require('packages/telescope-setup')
require('packages/tasks-setup')
require('packages/tagbar-setup')
require('packages/todo-setup')
require('packages/colorizer-setup')
require('packages/treesitter-setup')
require('packages/dap-setup')

